import { useState, useEffect } from 'react';

const translations = {
  'Português (BR)': {
    // Sidebar
    home: 'Início',
    search: 'Buscar',
    profile: 'Meu Perfil',
    settings: 'Configurações',
    // Feed
    feedTitle: 'INÍCIO',
    whatThinking: 'No que você está pensando?',
    publish: 'Publicar',
    comments: 'comentários',
    reposts: 'reposts',
    likes: 'curtidas',
    noPosts: 'Nenhuma publicação por aqui ainda.',
    noComments: 'Nenhum comentário ainda. Seja o primeiro!',
    commentPlaceholder: 'Escreva um comentário...',
    commentBtn: 'Comentar',
    loading: 'Carregando...',
    // Mural / Buscar
    searchTitle: 'BUSCAR',
    muralTitle: 'Mural Acadêmico',
    noAnnouncements: 'Nenhum aviso encontrado.',
    createAnnouncement: 'Criar Aviso',
    // Perfil
    editProfile: 'Editar Perfil',
    followers: 'seguidores',
    following: 'seguindo',
    teacher: '🎓 Docente',
    student: '📖 Discente',
    postsTab: 'Posts',
    repostsTab: 'Reposts',
    follow: 'Seguir',
    unfollow: 'Seguindo',
    // Mensagens
    messagesTitle: 'MENSAGENS',
    searchContacts: 'Buscar contatos...',
    contactsAvailable: 'CONTACTOS DISPONÍVEIS',
    noContacts: 'Nenhum contato encontrado.',
    connected: 'Conectado',
    chatPlaceholder: 'Conversar com',
    voiceMsg: 'Mensagem de voz',
    calling: 'Chamando...',
    callConnected: 'Conectado',
    callProtected: 'Chamada Protegida',
    callEncrypted: 'Criptografada de ponta a ponta',
    micMute: 'Desativar Microfone',
    micUnmute: 'Ativar Microfone',
    camMute: 'Desativar Câmera',
    camUnmute: 'Ativar Câmera',
    endCall: 'Desligar Chamada',
    // Configuracoes
    settingsTitle: 'CONFIGURAÇÕES',
    security: 'Segurança',
    changePassword: 'Alterar senha',
    twoFactor: 'Verificação em duas etapas (2FA)',
    recoveryEmail: 'E-mail de recuperação',
    privacy: 'Privacidade',
    privateAccount: 'Conta privada',
    hideActivity: 'Ocultar minha atividade',
    whoMention: 'Quem pode me mencionar',
    all: 'Todos',
    onlyFollowers: 'Apenas Seguidores',
    nobody: 'Ninguém',
    nightMode: 'Modo Noturno',
    accessibility: 'Acessibilidade & Interface',
    highContrast: 'Aumentar contraste de cores',
    textSize: 'Tamanho do texto global',
    small: 'pequena',
    medium: 'média',
    large: 'grande',
    systemLanguage: 'Idioma do sistema',
    logout: 'sair da conta',
  },
  'English': {
    home: 'Home',
    search: 'Search',
    profile: 'My Profile',
    settings: 'Settings',
    feedTitle: 'HOME',
    whatThinking: "What's on your mind?",
    publish: 'Publish',
    comments: 'comments',
    reposts: 'reposts',
    likes: 'likes',
    noPosts: 'No posts around here yet.',
    noComments: 'No comments yet. Be the first!',
    commentPlaceholder: 'Write a comment...',
    commentBtn: 'Comment',
    loading: 'Loading...',
    searchTitle: 'SEARCH',
    muralTitle: 'Academic Wall',
    noAnnouncements: 'No announcements found.',
    createAnnouncement: 'Create Announcement',
    editProfile: 'Edit Profile',
    followers: 'followers',
    following: 'following',
    teacher: '🎓 Faculty',
    student: '📖 Student',
    postsTab: 'Posts',
    repostsTab: 'Reposts',
    follow: 'Follow',
    unfollow: 'Following',
    messagesTitle: 'MESSAGES',
    searchContacts: 'Search contacts...',
    contactsAvailable: 'AVAILABLE CONTACTS',
    noContacts: 'No contacts found.',
    connected: 'Connected',
    chatPlaceholder: 'Chat with',
    voiceMsg: 'Voice message',
    calling: 'Calling...',
    callConnected: 'Connected',
    callProtected: 'Secure Call',
    callEncrypted: 'End-to-end encrypted',
    micMute: 'Mute Microphone',
    micUnmute: 'Unmute Microphone',
    camMute: 'Mute Camera',
    camUnmute: 'Unmute Camera',
    endCall: 'End Call',
    settingsTitle: 'SETTINGS',
    security: 'Security',
    changePassword: 'Change password',
    twoFactor: 'Two-factor verification (2FA)',
    recoveryEmail: 'Recovery email',
    privacy: 'Privacy',
    privateAccount: 'Private account',
    hideActivity: 'Hide my activity',
    whoMention: 'Who can mention me',
    all: 'Everyone',
    onlyFollowers: 'Only Followers',
    nobody: 'Nobody',
    nightMode: 'Dark Mode',
    accessibility: 'Accessibility & Interface',
    highContrast: 'Increase color contrast',
    textSize: 'Global text size',
    small: 'small',
    medium: 'medium',
    large: 'large',
    systemLanguage: 'System language',
    logout: 'logout',
  },
  'Español': {
    home: 'Inicio',
    search: 'Buscar',
    profile: 'Mi Perfil',
    settings: 'Configuración',
    feedTitle: 'INICIO',
    whatThinking: '¿En qué estás pensando?',
    publish: 'Publicar',
    comments: 'comentarios',
    reposts: 'reposts',
    likes: 'me gusta',
    noPosts: 'No hay publicaciones por aquí todavía.',
    noComments: 'Sin comentarios aún. ¡Sé el primero!',
    commentPlaceholder: 'Escribe un comentario...',
    commentBtn: 'Comentar',
    loading: 'Cargando...',
    searchTitle: 'BUSCAR',
    muralTitle: 'Muro Académico',
    noAnnouncements: 'No se encontraron avisos.',
    createAnnouncement: 'Crear Aviso',
    editProfile: 'Editar Perfil',
    followers: 'seguidores',
    following: 'siguiendo',
    teacher: '🎓 Docente',
    student: '📖 Estudiante',
    postsTab: 'Publicaciones',
    repostsTab: 'Reposts',
    follow: 'Seguir',
    unfollow: 'Siguiendo',
    messagesTitle: 'MENSAJES',
    searchContacts: 'Buscar contactos...',
    contactsAvailable: 'CONTACTOS DISPONIBLES',
    noContacts: 'No se encontraron contactos.',
    connected: 'Conectado',
    chatPlaceholder: 'Chatear con',
    voiceMsg: 'Mensaje de voz',
    calling: 'Llamando...',
    callConnected: 'Conectado',
    callProtected: 'Llamada Protegida',
    callEncrypted: 'Encriptada de extremo a extremo',
    micMute: 'Silenciar Micrófono',
    micUnmute: 'Activar Micrófono',
    camMute: 'Desactivar Cámara',
    camUnmute: 'Activar Cámara',
    endCall: 'Terminar Llamada',
    settingsTitle: 'CONFIGURACIÓN',
    security: 'Seguridad',
    changePassword: 'Cambiar contraseña',
    twoFactor: 'Verificación en dos pasos (2FA)',
    recoveryEmail: 'Correo de recuperación',
    privacy: 'Privacidad',
    privateAccount: 'Cuenta privada',
    hideActivity: 'Ocultar mi actividad',
    whoMention: 'Quién puede mencionarme',
    all: 'Todos',
    onlyFollowers: 'Solo Seguidores',
    nobody: 'Nadie',
    nightMode: 'Modo Oscuro',
    accessibility: 'Accesibilidad e Interfaz',
    highContrast: 'Aumentar contraste de colores',
    textSize: 'Tamaño de texto global',
    small: 'pequeño',
    medium: 'mediano',
    large: 'grande',
    systemLanguage: 'Idioma del sistema',
    logout: 'cerrar sesión',
  },
  'Français': {
    home: 'Accueil',
    search: 'Rechercher',
    profile: 'Mon Profil',
    settings: 'Paramètres',
    feedTitle: 'ACCUEIL',
    whatThinking: 'À quoi pensez-vous?',
    publish: 'Publier',
    comments: 'commentaires',
    reposts: 'reposts',
    likes: 'mentions j’aime',
    noPosts: 'Aucune publication ici pour le moment.',
    noComments: 'Aucun commentaire pour le moment. Soyez le premier!',
    commentPlaceholder: 'Écrire un commentaire...',
    commentBtn: 'Commenter',
    loading: 'Chargement...',
    searchTitle: 'RECHERCHE',
    muralTitle: 'Mur Académique',
    noAnnouncements: 'Aucune annonce trouvée.',
    createAnnouncement: 'Créer une annonce',
    editProfile: 'Modifier le profil',
    followers: 'abonnés',
    following: 'abonnements',
    teacher: '🎓 Enseignant',
    student: '📖 Étudiant',
    postsTab: 'Publications',
    repostsTab: 'Reposts',
    follow: 'Suivre',
    unfollow: 'Abonné',
    messagesTitle: 'MESSAGES',
    searchContacts: 'Rechercher des contacts...',
    contactsAvailable: 'CONTACTS DISPONIBLES',
    noContacts: 'Aucun contact trouvé.',
    connected: 'En ligne',
    chatPlaceholder: 'Discuter avec',
    voiceMsg: 'Message vocal',
    calling: 'Appel en cours...',
    callConnected: 'Connecté',
    callProtected: 'Appel Sécurisé',
    callEncrypted: 'Chiffré de bout en bout',
    micMute: 'Couper le micro',
    micUnmute: 'Activer le micro',
    camMute: 'Désactiver la caméra',
    camUnmute: 'Activer la caméra',
    endCall: 'Raccrocher',
    settingsTitle: 'PARAMÈTRES',
    security: 'Sécurité',
    changePassword: 'Modifier le mot de passe',
    twoFactor: 'Validation en deux étapes (2FA)',
    recoveryEmail: 'E-mail de récupération',
    privacy: 'Confidentialité',
    privateAccount: 'Compte privé',
    hideActivity: 'Masquer mon activité',
    whoMention: 'Qui peut me mentionner',
    all: 'Tout le monde',
    onlyFollowers: 'Seulement les abonnés',
    nobody: 'Personne',
    nightMode: 'Mode Sombre',
    accessibility: 'Accessibilité & Interface',
    highContrast: 'Augmenter le contraste',
    textSize: 'Taille du texte global',
    small: 'petite',
    medium: 'moyenne',
    large: 'grande',
    systemLanguage: 'Langue du système',
    logout: 'se déconnecter',
  },
  'Deutsch': {
    home: 'Startseite',
    search: 'Suche',
    profile: 'Mein Profil',
    settings: 'Einstellungen',
    feedTitle: 'STARTSEITE',
    whatThinking: 'Was geht dir durch den Kopf?',
    publish: 'Veröffentlichen',
    comments: 'Kommentare',
    reposts: 'Reposts',
    likes: 'Gefällt mir',
    noPosts: 'Hier gibt es noch keine Beiträge.',
    noComments: 'Noch keine Kommentare. Schreibe den ersten!',
    commentPlaceholder: 'Einen Kommentar schreiben...',
    commentBtn: 'Kommentieren',
    loading: 'Laden...',
    searchTitle: 'SUCHE',
    muralTitle: 'Akademische Pinnwand',
    noAnnouncements: 'Keine Ankündigungen gefunden.',
    createAnnouncement: 'Ankündigung erstellen',
    editProfile: 'Profil bearbeiten',
    followers: 'Follower',
    following: 'Gefolgt',
    teacher: '🎓 Lehrkraft',
    student: '📖 Student',
    postsTab: 'Beiträge',
    repostsTab: 'Reposts',
    follow: 'Folgen',
    unfollow: 'Gefolgt',
    messagesTitle: 'NACHRICHTEN',
    searchContacts: 'Kontakte suchen...',
    contactsAvailable: 'VERFÜGBARE KONTAKTE',
    noContacts: 'Keine Kontakte gefunden.',
    connected: 'Online',
    chatPlaceholder: 'Chatten mit',
    voiceMsg: 'Sprachnachricht',
    calling: 'Anrufen...',
    callConnected: 'Verbunden',
    callProtected: 'Gesichertes Telefonat',
    callEncrypted: 'Ende-zu-Ende verschlüsselt',
    micMute: 'Stummschalten',
    micUnmute: 'Mikrofon aktivieren',
    camMute: 'Kamera ausschalten',
    camUnmute: 'Kamera einschalten',
    endCall: 'Auflegen',
    settingsTitle: 'EINSTELLUNGEN',
    security: 'Sicherheit',
    changePassword: 'Passwort ändern',
    twoFactor: 'Zwei-Faktor-Authentifizierung (2FA)',
    recoveryEmail: 'Wiederherstellungs-E-Mail',
    privacy: 'Privatsphäre',
    privateAccount: 'Privates Konto',
    hideActivity: 'Aktivitätsstatus verbergen',
    whoMention: 'Wer kann mich erwähnen',
    all: 'Jeder',
    onlyFollowers: 'Nur Follower',
    nobody: 'Niemand',
    nightMode: 'Dunkelmodus',
    accessibility: 'Barrierefreiheit & Interface',
    highContrast: 'Farbkontrast erhöhen',
    textSize: 'Globale Textgröße',
    small: 'klein',
    medium: 'mittel',
    large: 'groß',
    systemLanguage: 'Systemsprache',
    logout: 'abmelden',
  },
  'Italiano': {
    home: 'Home',
    search: 'Cerca',
    profile: 'Il Mio Profilo',
    settings: 'Impostazioni',
    feedTitle: 'HOME',
    whatThinking: 'A cosa stai pensando?',
    publish: 'Pubblica',
    comments: 'commenti',
    reposts: 'repost',
    likes: 'mi piace',
    noPosts: 'Non ci sono ancora post qui.',
    noComments: 'Ancora nessun commento. Scrivi il primo!',
    commentPlaceholder: 'Scrivi un commento...',
    commentBtn: 'Commenta',
    loading: 'Caricamento...',
    searchTitle: 'CERCA',
    muralTitle: 'Bacheca Accademica',
    noAnnouncements: 'Nessun annuncio trovato.',
    createAnnouncement: 'Crea Annuncio',
    editProfile: 'Modifica Profilo',
    followers: 'follower',
    following: 'seguiti',
    teacher: '🎓 Docente',
    student: '📖 Studente',
    postsTab: 'Post',
    repostsTab: 'Repost',
    follow: 'Segui',
    unfollow: 'Segui già',
    messagesTitle: 'MESSAGGI',
    searchContacts: 'Cerca contatti...',
    contactsAvailable: 'CONTATTI DISPONIBILI',
    noContacts: 'Nessun contatto trovato.',
    connected: 'Connesso',
    chatPlaceholder: 'Chatta con',
    voiceMsg: 'Messaggio vocale',
    calling: 'Chiamata in corso...',
    callConnected: 'Connesso',
    callProtected: 'Chiamata Protetta',
    callEncrypted: 'Crittografato end-to-end',
    micMute: 'Disattiva microfono',
    micUnmute: 'Attiva microfono',
    camMute: 'Disattiva fotocamera',
    camUnmute: 'Attiva fotocamera',
    endCall: 'Termina Chiamata',
    settingsTitle: 'IMPOSTAZIONI',
    security: 'Sicurezza',
    changePassword: 'Cambia password',
    twoFactor: 'Verifica in due passaggi (2FA)',
    recoveryEmail: 'E-mail di recupero',
    privacy: 'Privacy',
    privateAccount: 'Account privato',
    hideActivity: 'Nascondi la mia attività',
    whoMention: 'Chi può menzionarmi',
    all: 'Tutti',
    onlyFollowers: 'Solo Follower',
    nobody: 'Nessuno',
    nightMode: 'Modalità Scura',
    accessibility: 'Accessibilità e Interfaccia',
    highContrast: 'Aumenta contrasto colori',
    textSize: 'Dimensione testo globale',
    small: 'piccolo',
    medium: 'medio',
    large: 'grande',
    systemLanguage: 'Lingua del sistema',
    logout: 'disconnettiti',
  },
  '日本語': {
    home: 'ホーム',
    search: '検索',
    profile: 'プロフィール',
    settings: '設定',
    feedTitle: 'ホーム',
    whatThinking: '今何してる？',
    publish: '投稿する',
    comments: '件のコメント',
    reposts: '件のリポスト',
    likes: '件のいいね',
    noPosts: 'まだ投稿はありません。',
    noComments: 'コメントはまだありません。最初のコメントを書きましょう！',
    commentPlaceholder: 'コメントを書く...',
    commentBtn: '送信',
    loading: '読み込み中...',
    searchTitle: '検索',
    muralTitle: '学術掲示板',
    noAnnouncements: 'お知らせはありません。',
    createAnnouncement: 'お知らせ作成',
    editProfile: 'プロフィール編集',
    followers: 'フォロワー',
    following: 'フォロー中',
    teacher: '🎓 教員',
    student: '📖 学生',
    postsTab: '投稿',
    repostsTab: 'リポスト',
    follow: 'フォローする',
    unfollow: 'フォロー中',
    messagesTitle: 'メッセージ',
    searchContacts: '連絡先を検索...',
    contactsAvailable: '連絡可能リスト',
    noContacts: '連絡先が見つかりません。',
    connected: '接続中',
    chatPlaceholder: 'チャットする',
    voiceMsg: 'ボイスメッセージ',
    calling: '発信中...',
    callConnected: '通話中',
    callProtected: '保護された通話',
    callEncrypted: 'エンドツーエンドで暗号化',
    micMute: 'マイク消音',
    micUnmute: 'マイクオン',
    camMute: 'カメラオフ',
    camUnmute: 'カメラオン',
    endCall: '通話を終了',
    settingsTitle: '設定',
    security: 'セキュリティ',
    changePassword: 'パスワード変更',
    twoFactor: '二要素認証 (2FA)',
    recoveryEmail: '復旧用メールアドレス',
    privacy: 'プライバシー',
    privateAccount: '非公開アカウント',
    hideActivity: 'アクティビティステータス非表示',
    whoMention: '自分をメンションできる人',
    all: '全員',
    onlyFollowers: 'フォロワーのみ',
    nobody: '許可しない',
    nightMode: 'ダークモード',
    accessibility: 'アクセシビリティとUI設定',
    highContrast: 'ハイコントラストモード',
    textSize: '全体の文字サイズ',
    small: '小',
    medium: '中',
    large: '大',
    systemLanguage: 'システム言語',
    logout: 'ログアウト',
  },
  '中文': {
    home: '首页',
    search: '搜索',
    profile: '个人主页',
    settings: '设置',
    feedTitle: '首页',
    whatThinking: '分享你的新鲜事...',
    publish: '发布',
    comments: '条评论',
    reposts: '次转发',
    likes: '次赞',
    noPosts: '目前还没有动态。',
    noComments: '暂无评论。来发表第一条评论吧！',
    commentPlaceholder: '写下你的评论...',
    commentBtn: '评论',
    loading: '加载中...',
    searchTitle: '搜索',
    muralTitle: '学术公告栏',
    noAnnouncements: '未找到公告。',
    createAnnouncement: '发布公告',
    editProfile: '编辑个人资料',
    followers: '粉丝',
    following: '关注',
    teacher: '🎓 教师',
    student: '📖 学生',
    postsTab: '动态',
    repostsTab: '转发',
    follow: '关注',
    unfollow: '已关注',
    messagesTitle: '消息',
    searchContacts: '搜索联系人...',
    contactsAvailable: '联系人列表',
    noContacts: '未找到联系人。',
    connected: '在线',
    chatPlaceholder: '聊天人：',
    voiceMsg: '语音消息',
    calling: '呼叫中...',
    callConnected: '已接通',
    callProtected: '安全通话',
    callEncrypted: '端到端加密',
    micMute: '静音',
    micUnmute: '取消静音',
    camMute: '关闭摄像头',
    camUnmute: '开启摄像头',
    endCall: '挂断',
    settingsTitle: '设置',
    security: '安全',
    changePassword: '修改密码',
    twoFactor: '双重身份验证 (2FA)',
    recoveryEmail: '密保邮箱',
    privacy: '隐私',
    privateAccount: '私密账户',
    hideActivity: '隐藏活动状态',
    whoMention: '谁可以提及我',
    all: '所有人',
    onlyFollowers: '仅关注我的人',
    nobody: '无人',
    nightMode: '夜间模式',
    accessibility: '无障碍与界面',
    highContrast: '高对比度',
    textSize: '全局文字大小',
    small: '小',
    medium: '中',
    large: '大',
    systemLanguage: '系统语言',
    logout: '退出登录',
  },
  'Русский': {
    home: 'Главная',
    search: 'Поиск',
    profile: 'Мой Профиль',
    settings: 'Настройки',
    feedTitle: 'ГЛАВНАЯ',
    whatThinking: 'Что у вас нового?',
    publish: 'Опубликовать',
    comments: 'коммент.',
    reposts: 'репостов',
    likes: 'лайков',
    noPosts: 'Здесь пока нет публикаций.',
    noComments: 'Комментариев пока нет. Будьте первым!',
    commentPlaceholder: 'Написать комментарий...',
    commentBtn: 'Комментировать',
    loading: 'Загрузка...',
    searchTitle: 'ПОИСК',
    muralTitle: 'Академическая доска',
    noAnnouncements: 'Объявлений не найдено.',
    createAnnouncement: 'Создать объявление',
    editProfile: 'Редактировать профиль',
    followers: 'подписчиков',
    following: 'подписок',
    teacher: '🎓 Преподаватель',
    student: '📖 Студент',
    postsTab: 'Публикации',
    repostsTab: 'Репосты',
    follow: 'Подписаться',
    unfollow: 'Вы подписаны',
    messagesTitle: 'СООБЩЕНИЯ',
    searchContacts: 'Поиск контактов...',
    contactsAvailable: 'ДОСТУПНЫЕ КОНТАКТЫ',
    noContacts: 'Контакты не найдены.',
    connected: 'В сети',
    chatPlaceholder: 'Чат с',
    voiceMsg: 'Голосовое сообщение',
    calling: 'Звонок...',
    callConnected: 'Соединено',
    callProtected: 'Защищенный звонок',
    callEncrypted: 'Сквозное шифрование',
    micMute: 'Выключить микрофон',
    micUnmute: 'Включить микрофон',
    camMute: 'Выключить камеру',
    camUnmute: 'Включить камеру',
    endCall: 'Завершить звонок',
    settingsTitle: 'НАСТРОЙКИ',
    security: 'Безопасность',
    changePassword: 'Сменить пароль',
    twoFactor: 'Двухфакторная аутентификация (2FA)',
    recoveryEmail: 'Резервный e-mail',
    privacy: 'Конфиденциальность',
    privateAccount: 'Закрытый аккаунт',
    hideActivity: 'Скрыть мою активность',
    whoMention: 'Кто может упоминать меня',
    all: 'Все',
    onlyFollowers: 'Только подписчики',
    nobody: 'Никто',
    nightMode: 'Темная тема',
    accessibility: 'Доступность и Интерфейс',
    highContrast: 'Увеличить контрастность',
    textSize: 'Размер текста',
    small: 'мелкий',
    medium: 'средний',
    large: 'крупный',
    systemLanguage: 'Язык системы',
    logout: 'выйти из аккаунта',
  },
  'العربية': {
    home: 'الرئيسية',
    search: 'بحث',
    profile: 'الملف الشخصي',
    settings: 'الإعدادات',
    feedTitle: 'الرئيسية',
    whatThinking: 'بمَ تفكر؟',
    publish: 'نشر',
    comments: 'تعليقات',
    reposts: 'إعادات نشر',
    likes: 'إعجابات',
    noPosts: 'لا توجد منشورات هنا بعد.',
    noComments: 'لا توجد تعليقات بعد. كن أول من يعلق!',
    commentPlaceholder: 'اكتب تعليقًا...',
    commentBtn: 'تعليق',
    loading: 'جاري التحميل...',
    searchTitle: 'بحث',
    muralTitle: 'المجلس الأكاديمي',
    noAnnouncements: 'لم يتم العثور على إعلانات.',
    createAnnouncement: 'إنشاء إعلان',
    editProfile: 'تعديل الملف الشخصي',
    followers: 'متابعون',
    following: 'متابعة',
    teacher: '🎓 أستاذ',
    student: '📖 طالب',
    postsTab: 'المنشورات',
    repostsTab: 'إعادات النشر',
    follow: 'متابعة',
    unfollow: 'متابع',
    messagesTitle: 'الرسائل',
    searchContacts: 'البحث عن جهات اتصال...',
    contactsAvailable: 'جهات الاتصال المتاحة',
    noContacts: 'لم يتم العثور على جهات اتصال.',
    connected: 'نشط الآن',
    chatPlaceholder: 'دردشة مع',
    voiceMsg: 'رسالة صوتية',
    calling: 'جاري الاتصال...',
    callConnected: 'تم الاتصال',
    callProtected: 'مكالمة آمنة',
    callEncrypted: 'مشفرة من الطرفين',
    micMute: 'كتم الميكروفون',
    micUnmute: 'تفعيل الميكروفون',
    camMute: 'إيقاف الكاميرا',
    camUnmute: 'تشغيل الكاميرا',
    endCall: 'إنهاء المكالمة',
    settingsTitle: 'الإعدادات',
    security: 'الأمان',
    changePassword: 'تغيير كلمة المرور',
    twoFactor: 'التحقق بخطوتين (2FA)',
    recoveryEmail: 'بريد الاسترداد',
    privacy: 'الخصوصية',
    privateAccount: 'حساب خاص',
    hideActivity: 'إخفاء حالة النشاط',
    whoMention: 'من يمكنه الإشارة إلي',
    all: 'الجميع',
    onlyFollowers: 'المتابعون فقط',
    nobody: 'لا أحد',
    nightMode: 'الوضع الداكن',
    accessibility: 'سهولة الوصول والواجهة',
    highContrast: 'زيادة تباين الألوان',
    textSize: 'حجم النص العام',
    small: 'صغير',
    medium: 'متوسط',
    large: 'كبير',
    systemLanguage: 'لغة النظام',
    logout: 'تسجيل الخروج',
  },
  'हिन्दी': {
    home: 'होम',
    search: 'खोजें',
    profile: 'मेरी प्रोफ़ाइल',
    settings: 'सेटिंग्स',
    feedTitle: 'होम',
    whatThinking: 'आपके मन में क्या है?',
    publish: 'प्रकाशित करें',
    comments: 'टिप्पणियाँ',
    reposts: 'रीपोस्ट',
    likes: 'पसंद',
    noPosts: 'यहाँ अभी तक कोई पोस्ट नहीं है।',
    noComments: 'कोई टिप्पणी नहीं। पहली टिप्पणी करें!',
    commentPlaceholder: 'एक टिप्पणी लिखें...',
    commentBtn: 'टिप्पणी करें',
    loading: 'लोड हो रहा है...',
    searchTitle: 'खोजें',
    muralTitle: 'शैक्षणिक सूचना बोर्ड',
    noAnnouncements: 'कोई सूचना नहीं मिली।',
    createAnnouncement: 'सूचना बनाएं',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    followers: 'फ़ॉलोअर्स',
    following: 'फ़ॉলো कर रहे हैं',
    teacher: '🎓 शिक्षक',
    student: '📖 छात्र',
    postsTab: 'पोस्ट',
    repostsTab: 'रीपोस्ट',
    follow: 'फ़ॉलो करें',
    unfollow: 'फ़ॉলো कर रहे हैं',
    messagesTitle: 'संदेश',
    searchContacts: 'संपर्क खोजें...',
    contactsAvailable: 'उपलब्ध संपर्क',
    noContacts: 'कोई संपर्क नहीं मिला।',
    connected: 'ऑनलाइन',
    chatPlaceholder: 'बातचीत करें',
    voiceMsg: 'वॉयस संदेश',
    calling: 'कॉल हो रही है...',
    callConnected: 'कनेक्टेड',
    callProtected: 'सुरक्षित कॉल',
    callEncrypted: 'एंड-टू-एंड एन्क्रिप्टेड',
    micMute: 'म्यूट करें',
    micUnmute: 'अनम्यूट करें',
    camMute: 'कैमरा बंद करें',
    camUnmute: 'कैमरा चालू करें',
    endCall: 'कॉल समाप्त करें',
    settingsTitle: 'सेटिंग्स',
    security: 'सुरक्षा',
    changePassword: 'पासवर्ड बदलें',
    twoFactor: 'टू-फैक्टर प्रमाणीकरण (2FA)',
    recoveryEmail: 'रिकवरी ईमेल',
    privacy: 'गोपनीयता',
    privateAccount: 'निजी खाता',
    hideActivity: 'सक्रियता छुपाएं',
    whoMention: 'कौन मुझे मेंशन कर सकता है',
    all: 'सभी',
    onlyFollowers: 'केवल फ़ॉलोअर्स',
    nobody: 'कोई नहीं',
    nightMode: 'डार्क मोड',
    accessibility: 'एक्सेसिबिलिटी और इंटरफ़ेस',
    highContrast: 'रंग कंट्रास्ट बढ़ाएं',
    textSize: 'टेक्स्ट का आकार',
    small: 'छोटा',
    medium: 'मध्यम',
    large: 'बड़ा',
    systemLanguage: 'सिस्टम की भाषा',
    logout: 'लॉगआउट करें',
  },
  '한국어': {
    home: '홈',
    search: '검색',
    profile: '프로필',
    settings: '설정',
    feedTitle: '홈',
    whatThinking: '무슨 생각을 하고 계신가요?',
    publish: '게시',
    comments: '개의 댓글',
    reposts: '개의 리포스트',
    likes: '개의 좋아요',
    noPosts: '아직 게시물이 없습니다.',
    noComments: '댓글이 없습니다. 첫 댓글을 작성해보세요!',
    commentPlaceholder: '댓글 작성...',
    commentBtn: '게시',
    loading: '로딩 중...',
    searchTitle: '검색',
    muralTitle: '학술 게시판',
    noAnnouncements: '공지사항이 없습니다.',
    createAnnouncement: '공지 생성',
    editProfile: '프로필 편집',
    followers: '팔로워',
    following: '팔로잉',
    teacher: '🎓 교원',
    student: '📖 학생',
    postsTab: '게시물',
    repostsTab: '리포스트',
    follow: '팔로우',
    unfollow: '팔로잉 중',
    messagesTitle: '메시지',
    searchContacts: '연락처 검색...',
    contactsAvailable: '연락 가능 목록',
    noContacts: '연락처를 찾을 수 없습니다.',
    connected: '온라인',
    chatPlaceholder: '대화 상대:',
    voiceMsg: '음성 메시지',
    calling: '통화 연결 중...',
    callConnected: '연결됨',
    callProtected: '보안 통화',
    callEncrypted: '종단간 암호화됨',
    micMute: '음소거',
    micUnmute: '마이크 켜기',
    camMute: '카메라 끄기',
    camUnmute: '카메라 켜기',
    endCall: '통화 종료',
    settingsTitle: '설정',
    security: '보안',
    changePassword: '비밀번호 변경',
    twoFactor: '2단계 인증 (2FA)',
    recoveryEmail: '복구 이메일',
    privacy: '개인정보 보호',
    privateAccount: '비공개 계정',
    hideActivity: '활동 상태 숨기기',
    whoMention: '나를 멘션할 수 있는 사람',
    all: '모두',
    onlyFollowers: '팔로워만',
    nobody: '허용 안 함',
    nightMode: '다크 모드',
    accessibility: '접근성 및 인터페이스',
    highContrast: '색상 대비 증가',
    textSize: '글자 크기',
    small: '작게',
    medium: '보통',
    large: '크게',
    systemLanguage: '시스템 언어',
    logout: '로그아웃',
  }
};

const extraTranslations = {
  'Português (BR)': {
    notificationsTitle: 'NOTIFICAÇÕES',
    newPostTitle: 'NOVA PUBLICAÇÃO',
    newAnnouncementTitle: 'NOVO AVISO',
    profileTitle: 'PERFIL',
    commentsTitle: 'Comentários',
    close: 'Fechar',
    postsLabel: 'posts',
    registration: 'Matrícula',
    noBio: 'Nenhuma apresentação disponível ainda no ecossistema.',
    message: 'Mensagem',
    repostedBy: 'republicado de',
    noReposts: 'Nenhum repost compartilhado ainda.',
    profileNotFound: 'Perfil não encontrado.',
    back: 'Voltar',
    audioCall: 'Ligação de Áudio',
    videoCall: 'Ligação de Vídeo',
    blockUser: 'Bloquear Usuário',
    unblockUser: 'Desbloquear Usuário',
    blockedContact: 'Contato Bloqueado',
    blockedContactDesc: 'Você bloqueou este usuário. Para enviar mensagens de texto, anexos, emojis ou iniciar chamadas, é necessário desbloqueá-lo.',
    recordingVoice: 'Gravando voz...',
    cancel: 'Cancelar',
    sendAudio: 'Enviar Áudio',
    sendImage: 'Enviar Imagem',
    emojis: 'Emojis',
    recordVoiceMsg: 'Gravar Mensagem de Voz',
    yourConversations: 'Suas conversas',
    selectContactDesc: 'Selecione um contato na barra lateral para abrir um chat seguro e privado.',
    protectedVideoCall: 'Chamada de Vídeo Protegida',
    protectedAudioCall: 'Chamada de Áudio Protegida',
    postTitleLabel: 'Título da publicação',
    postContentLabel: 'O que você quer compartilhar? (Opcional)',
    postContentPlaceholder: 'Escreva aqui os detalhes, links ou avisos da sua postagem...',
    coverImageLabel: 'Imagem de capa (Opcional)',
    clickSelectImage: 'Clique para selecionar uma imagem',
    uploading: 'Fazendo upload...',
    publishing: 'Publicando...',
    publishBtnText: 'Publicar no EduConnect',
    onlyTeachersCanCreateAnnouncements: 'Acesso negado: Apenas professores podem criar avisos.',
    validatingTeacherCredentials: 'Validando credenciais docentes...',
    publishingAs: 'Publicando como',
    subjectLabel: 'Matéria / Disciplina',
    subjectPlaceholder: 'Ex: BANCO DE DADOS, ALGORITMOS...',
    announcementTitleLabel: 'Título do Aviso',
    announcementTitlePlaceholder: 'Ex: Prova adiada, Material disponível...',
    announcementContentLabel: 'Conteúdo do Informativo',
    announcementContentPlaceholder: 'Digite os detalhes do comunicado para los alunos...',
    publishingAnnouncement: 'Disparando Comunicado...',
    publishAnnouncementBtn: 'Publicar no Mural'
  },
  'English': {
    notificationsTitle: 'NOTIFICATIONS',
    newPostTitle: 'NEW POST',
    newAnnouncementTitle: 'NEW ANNOUNCEMENT',
    profileTitle: 'PROFILE',
    commentsTitle: 'Comments',
    close: 'Close',
    postsLabel: 'posts',
    registration: 'Registration',
    noBio: 'No presentation available in the ecosystem yet.',
    message: 'Message',
    repostedBy: 'reposted from',
    noReposts: 'No repost shared yet.',
    profileNotFound: 'Profile not found.',
    back: 'Back',
    audioCall: 'Audio Call',
    videoCall: 'Video Call',
    blockUser: 'Block User',
    unblockUser: 'Unblock User',
    blockedContact: 'Blocked Contact',
    blockedContactDesc: 'You blocked this user. To send text messages, attachments, emojis or start calls, you need to unblock them.',
    recordingVoice: 'Recording voice...',
    cancel: 'Cancel',
    sendAudio: 'Send Audio',
    sendImage: 'Send Image',
    emojis: 'Emojis',
    recordVoiceMsg: 'Record Voice Message',
    yourConversations: 'Your conversations',
    selectContactDesc: 'Select a contact in the sidebar to open a secure and private chat.',
    protectedVideoCall: 'Secure Video Call',
    protectedAudioCall: 'Secure Audio Call',
    postTitleLabel: 'Post Title',
    postContentLabel: 'What do you want to share? (Optional)',
    postContentPlaceholder: 'Write here the details, links or announcements of your post...',
    coverImageLabel: 'Cover image (Optional)',
    clickSelectImage: 'Click to select an image',
    uploading: 'Uploading...',
    publishing: 'Publishing...',
    publishBtnText: 'Publish to EduConnect',
    onlyTeachersCanCreateAnnouncements: 'Access denied: Only teachers can create announcements.',
    validatingTeacherCredentials: 'Validating teacher credentials...',
    publishingAs: 'Publishing as',
    subjectLabel: 'Subject / Discipline',
    subjectPlaceholder: 'Ex: DATABASE, ALGORITHMS...',
    announcementTitleLabel: 'Announcement Title',
    announcementTitlePlaceholder: 'Ex: Exam postponed, Material available...',
    announcementContentLabel: 'Announcement Content',
    announcementContentPlaceholder: 'Enter the details of the announcement for the students...',
    publishingAnnouncement: 'Publishing Announcement...',
    publishAnnouncementBtn: 'Publish to Wall'
  },
  'Español': {
    notificationsTitle: 'NOTIFICACIONES',
    newPostTitle: 'NUEVA PUBLICACIÓN',
    newAnnouncementTitle: 'NUEVO ANUNCIO',
    profileTitle: 'PERFIL',
    commentsTitle: 'Comentarios',
    close: 'Cerrar',
    postsLabel: 'posts',
    registration: 'Matrícula',
    noBio: 'Ninguna presentación disponible todavía en el ecosistema.',
    message: 'Mensaje',
    repostedBy: 'republicado de',
    noReposts: 'Ningún repost compartido todavía.',
    profileNotFound: 'Perfil no encontrado.',
    back: 'Volver',
    audioCall: 'Llamada de Audio',
    videoCall: 'Llamada de Video',
    blockUser: 'Bloquear Usuario',
    unblockUser: 'Desbloquear Usuario',
    blockedContact: 'Contacto Bloqueado',
    blockedContactDesc: 'Has bloqueado a este usuario. Para enviar mensajes de texto, archivos adjuntos, emojis o iniciar llamadas, debes desbloquearlo.',
    recordingVoice: 'Grabando voz...',
    cancel: 'Cancelar',
    sendAudio: 'Enviar Audio',
    sendImage: 'Enviar Imagen',
    emojis: 'Emojis',
    recordVoiceMsg: 'Grabar Mensaje de Voz',
    yourConversations: 'Tus conversaciones',
    selectContactDesc: 'Selecciona un contacto en la barra lateral para abrir un chat seguro y privado.',
    protectedVideoCall: 'Llamada de Video Protegida',
    protectedAudioCall: 'Llamada de Audio Protegida',
    postTitleLabel: 'Título de la publicación',
    postContentLabel: '¿Qué quieres compartir? (Opcional)',
    postContentPlaceholder: 'Escribe aquí los detalles, enlaces o avisos de tu publicación...',
    coverImageLabel: 'Imagen de portada (Opcional)',
    clickSelectImage: 'Haz clic para seleccionar una imagen',
    uploading: 'Subiendo...',
    publishing: 'Publicando...',
    publishBtnText: 'Publicar en EduConnect',
    onlyTeachersCanCreateAnnouncements: 'Acceso denegado: Solo los profesores pueden crear avisos.',
    validatingTeacherCredentials: 'Validando credenciales docentes...',
    publishingAs: 'Publicando como',
    subjectLabel: 'Materia / Asignatura',
    subjectPlaceholder: 'Ej: BASE DE DATOS, ALGORITMOS...',
    announcementTitleLabel: 'Título del Aviso',
    announcementTitlePlaceholder: 'Ej: Examen pospuesto, Material disponible...',
    announcementContentLabel: 'Contenido del Informativo',
    announcementContentPlaceholder: 'Ingresa los detalles del comunicado para los estudiantes...',
    publishingAnnouncement: 'Publicando Comunicado...',
    publishAnnouncementBtn: 'Publicar en el Muro'
  },
  'Français': {
    notificationsTitle: 'NOTIFICATIONS',
    newPostTitle: 'NOUVELLE PUBLICATION',
    newAnnouncementTitle: 'NOUVELLE ANNONCE',
    profileTitle: 'PROFIL',
    commentsTitle: 'Commentaires',
    close: 'Fermer',
    postsLabel: 'posts',
    registration: 'Matricule',
    noBio: 'Aucune présentation disponible dans l\'écosystème pour le moment.',
    message: 'Message',
    repostedBy: 'republié de',
    noReposts: 'Aucun repost partagé pour le moment.',
    profileNotFound: 'Profil introuvable.',
    back: 'Retour',
    audioCall: 'Appel audio',
    videoCall: 'Appel vidéo',
    blockUser: 'Bloquer l\'utilisateur',
    unblockUser: 'Débloquer l\'utilisateur',
    blockedContact: 'Contact bloqué',
    blockedContactDesc: 'Vous avez bloqué cet utilisateur. Pour envoyer des messages texte, des pièces jointes, des emojis ou démarrer des appels, vous devez le débloquer.',
    recordingVoice: 'Enregistrement de la voix...',
    cancel: 'Annuler',
    sendAudio: 'Envoyer l\'audio',
    sendImage: 'Envoyer l\'image',
    emojis: 'Emojis',
    recordVoiceMsg: 'Enregistrer un message vocal',
    yourConversations: 'Vos conversations',
    selectContactDesc: 'Sélectionnez un contact dans la barre latérale pour ouvrir un chat sécurisé et privé.',
    protectedVideoCall: 'Appel vidéo sécurisé',
    protectedAudioCall: 'Appel audio sécurisé',
    postTitleLabel: 'Titre de la publication',
    postContentLabel: 'Que voulez-vous partager? (Optionnel)',
    postContentPlaceholder: 'Écrivez ici les détails, liens ou annonces de votre publication...',
    coverImageLabel: 'Image de couverture (Optionnel)',
    clickSelectImage: 'Cliquez pour sélectionner une image',
    uploading: 'Téléchargement...',
    publishing: 'Publication...',
    publishBtnText: 'Publier sur EduConnect',
    onlyTeachersCanCreateAnnouncements: 'Accès refusé: Seuls les enseignants peuvent créer des annonces.',
    validatingTeacherCredentials: 'Validation des identifiants des enseignants...',
    publishingAs: 'Publié en tant que',
    subjectLabel: 'Matière / Discipline',
    subjectPlaceholder: 'Ex : BASE DE DONNÉES, ALGORITHMES...',
    announcementTitleLabel: 'Titre de l\'annonce',
    announcementTitlePlaceholder: 'Ex : Examen reporté, Matériel disponible...',
    announcementContentLabel: 'Contenu de l\'annonce',
    announcementContentPlaceholder: 'Saisissez les détails de l\'annonce pour les étudiants...',
    publishingAnnouncement: 'Publication de l\'annonce...',
    publishAnnouncementBtn: 'Publier sur le mur'
  },
  'Deutsch': {
    notificationsTitle: 'EINSTELLUNGEN', // wait, notifications is BENACHRICHTIGUNGEN
    newPostTitle: 'NEUER BEITRAG',
    newAnnouncementTitle: 'NEUE ANKÜNDIGUNG',
    profileTitle: 'PROFIL',
    commentsTitle: 'Kommentare',
    close: 'Schließen',
    postsLabel: 'Beiträge',
    registration: 'Matrikelnummer',
    noBio: 'Noch keine Beschreibung im System verfügbar.',
    message: 'Nachricht',
    repostedBy: 'reposted von',
    noReposts: 'Noch keine Reposts geteilt.',
    profileNotFound: 'Profil nicht gefunden.',
    back: 'Zurück',
    audioCall: 'Sprachanruf',
    videoCall: 'Videoanruf',
    blockUser: 'Benutzer blockieren',
    unblockUser: 'Benutzer entblocken',
    blockedContact: 'Blockierter Kontakt',
    blockedContactDesc: 'Sie haben diesen Benutzer blockiert. Um Textnachrichten, Anhänge, Emojis zu senden oder Anrufe zu starten, müssen Sie ihn entblocken.',
    recordingVoice: 'Stimme wird aufgenommen...',
    cancel: 'Abbrechen',
    sendAudio: 'Audio senden',
    sendImage: 'Bild senden',
    emojis: 'Emojis',
    recordVoiceMsg: 'Sprachnachricht aufnehmen',
    yourConversations: 'Ihre Unterhaltungen',
    selectContactDesc: 'Wählen Sie einen Kontakt in der Seitenleiste aus, um einen sicheren und privaten Chat zu öffnen.',
    protectedVideoCall: 'Gesicherter Videoanruf',
    protectedAudioCall: 'Gesicherter Sprachanruf',
    postTitleLabel: 'Titel des Beitrags',
    postContentLabel: 'Was möchten Sie teilen? (Optional)',
    postContentPlaceholder: 'Schreiben Sie hier Details, Links oder Ankündigungen Ihres Beitrags...',
    coverImageLabel: 'Titelbild (Optional)',
    clickSelectImage: 'Klicken, um ein Bild auszuwählen',
    uploading: 'Hochladen...',
    publishing: 'Veröffentlichen...',
    publishBtnText: 'In EduConnect veröffentlichen',
    onlyTeachersCanCreateAnnouncements: 'Zugriff verweigert: Nur Lehrer können Ankündigungen erstellen.',
    validatingTeacherCredentials: 'Lehrernachweise werden überprüft...',
    publishingAs: 'Veröffentlichen als',
    subjectLabel: 'Fach / Disziplin',
    subjectPlaceholder: 'Z.B.: DATENBANK, ALGORITHMEN...',
    announcementTitleLabel: 'Titel der Ankündigung',
    announcementTitlePlaceholder: 'Z.B.: Prüfung verschoben, Material verfügbar...',
    announcementContentLabel: 'Inhalt der Ankündigung',
    announcementContentPlaceholder: 'Geben Sie die Details der Ankündigung für die Schüler ein...',
    publishingAnnouncement: 'Ankündigung wird veröffentlicht...',
    publishAnnouncementBtn: 'Auf Pinnwand veröffentlichen'
  },
  'Italiano': {
    notificationsTitle: 'NOTIFICHE',
    newPostTitle: 'NUOVO POST',
    newAnnouncementTitle: 'NUOVO ANNUNCIO',
    profileTitle: 'PROFILO',
    commentsTitle: 'Commenti',
    close: 'Chiudi',
    postsLabel: 'post',
    registration: 'Matricola',
    noBio: 'Nessuna presentazione ancora disponibile nel sistema.',
    message: 'Messaggio',
    repostedBy: 'ripubblicato da',
    noReposts: 'Nessun repost condiviso ancora.',
    profileNotFound: 'Profilo non trovato.',
    back: 'Indietro',
    audioCall: 'Chiamata vocale',
    videoCall: 'Videoschiamata',
    blockUser: 'Blocca utente',
    unblockUser: 'Sblocca utente',
    blockedContact: 'Contatto bloccato',
    blockedContactDesc: 'Hai bloccato questo utente. Per inviare messaggi di testo, allegati, emoji o avviare chiamate, devi sbloccarlo.',
    recordingVoice: 'Registrazione vocale...',
    cancel: 'Annulla',
    sendAudio: 'Invia audio',
    sendImage: 'Invia immagine',
    emojis: 'Emoji',
    recordVoiceMsg: 'Registra messaggio vocale',
    yourConversations: 'Le tue conversazioni',
    selectContactDesc: 'Seleziona un contatto nella barra laterale per aprire una chat sicura e privata.',
    protectedVideoCall: 'Videoschiamata protetta',
    protectedAudioCall: 'Chiamata vocale protetta',
    postTitleLabel: 'Titolo del post',
    postContentLabel: 'Cosa vuoi condividere? (Opzionale)',
    postContentPlaceholder: 'Scrivi qui dettagli, link o annunci del tuo post...',
    coverImageLabel: 'Immagine di copertina (Opzionale)',
    clickSelectImage: 'Clicca per selezionare un\'immagine',
    uploading: 'Caricamento...',
    publishing: 'Pubblicazione...',
    publishBtnText: 'Pubblica su EduConnect',
    onlyTeachersCanCreateAnnouncements: 'Accesso negato: Solo i docenti possono creare annunci.',
    validatingTeacherCredentials: 'Convalida delle credenziali dei docenti...',
    publishingAs: 'Pubblicato come',
    subjectLabel: 'Materia / Disciplina',
    subjectPlaceholder: 'Es: DATABASE, ALGORITMI...',
    announcementTitleLabel: 'Titolo dell\'annuncio',
    announcementTitlePlaceholder: 'Es: Esame rimandato, Materiale disponibile...',
    announcementContentLabel: 'Contenuto dell\'annuncio',
    announcementContentPlaceholder: 'Inserisci i dettagli dell\'annuncio per gli studenti...',
    publishingAnnouncement: 'Pubblicazione dell\'annuncio...',
    publishAnnouncementBtn: 'Pubblica sulla bacheca'
  },
  '日本語': {
    notificationsTitle: '通知',
    newPostTitle: '新規投稿',
    newAnnouncementTitle: '新規お知らせ',
    profileTitle: 'プロフィール',
    commentsTitle: 'コメント',
    close: '閉じる',
    postsLabel: '投稿',
    registration: '学籍番号',
    noBio: '自己紹介はまだ登録されていません。',
    message: 'メッセージ',
    repostedBy: 'がリポストしました',
    noReposts: 'リポストはまだありません。',
    profileNotFound: 'プロフィールが見つかりません。',
    back: '戻る',
    audioCall: '音声通話',
    videoCall: 'ビデオ通話',
    blockUser: 'ユーザーをブロック',
    unblockUser: 'ユーザーのブロックを解除',
    blockedContact: 'ブロックされた連絡先',
    blockedContactDesc: 'このユーザーをブロックしました。テキストメッセージ、添付ファイル、絵文字の送信、または通話を開始するには、ブロックを解除する必要があります。',
    recordingVoice: '音声を録音中...',
    cancel: 'キャンセル',
    sendAudio: '音声を送信',
    sendImage: '画像を送信',
    emojis: '絵文字',
    recordVoiceMsg: 'ボイスメッセージを録音',
    yourConversations: 'チャット一覧',
    selectContactDesc: 'サイドバーから連絡先を選択して、安全でプライベートなチャットを開始します。',
    protectedVideoCall: '保護されたビデオ通話',
    protectedAudioCall: '保護された音声通話',
    postTitleLabel: '投稿タイトル',
    postContentLabel: '何を共有したいですか？（任意）',
    postContentPlaceholder: '投稿の詳細、リンク、お知らせなどをここに書いてください...',
    coverImageLabel: 'カバー画像（任意）',
    clickSelectImage: 'クリックして画像を選択',
    uploading: 'アップロード中...',
    publishing: '投稿中...',
    publishBtnText: 'EduConnectに投稿',
    onlyTeachersCanCreateAnnouncements: 'アクセス拒否：教員のみがおお知らせを作成できます。',
    validatingTeacherCredentials: '教員の資格情報を検証中...',
    publishingAs: '次として投稿中',
    subjectLabel: '教科 / 科目',
    subjectPlaceholder: '例：データベース、アルゴリズム...',
    announcementTitleLabel: 'お知らせのタイトル',
    announcementTitlePlaceholder: '例：試験延期、資料配布...',
    announcementContentLabel: 'お知らせの内容',
    announcementContentPlaceholder: '学生向けのお知らせの詳細を入力してください...',
    publishingAnnouncement: 'お知らせを投稿中...',
    publishAnnouncementBtn: '掲示板に投稿'
  },
  '中文': {
    notificationsTitle: '通知',
    newPostTitle: '新建动态',
    newAnnouncementTitle: '新建公告',
    profileTitle: '个人资料',
    commentsTitle: '评论',
    close: '关闭',
    postsLabel: '帖子',
    registration: '学号',
    noBio: '暂无个人介绍。',
    message: '发消息',
    repostedBy: '转发自',
    noReposts: '暂无转发的动态。',
    profileNotFound: '未找到个人资料。',
    back: '返回',
    audioCall: '语音通话',
    videoCall: '视频通话',
    blockUser: '拉黑用户',
    unblockUser: '取消拉黑',
    blockedContact: '已屏蔽的联系人',
    blockedContactDesc: '您已屏蔽此用户。要发送文本消息、附件、表情符号或发起通话，您需要先取消拉黑。',
    recordingVoice: '正在录音...',
    cancel: '取消',
    sendAudio: '发送音频',
    sendImage: '发送图片',
    emojis: '表情符号',
    recordVoiceMsg: '录制语音消息',
    yourConversations: '您的会话',
    selectContactDesc: '在侧边栏选择一个联系人以开启安全且私密的聊天。',
    protectedVideoCall: '安全视频通话',
    protectedAudioCall: '安全语音通话',
    postTitleLabel: '动态标题',
    postContentLabel: '你想分享什么？（可选）',
    postContentPlaceholder: '在此写下你动态的详细内容、链接或公告...',
    coverImageLabel: '封面图片（可选）',
    clickSelectImage: '点击选择图片',
    uploading: '正在上传...',
    publishing: '正在发布...',
    publishBtnText: '发布到 EduConnect',
    onlyTeachersCanCreateAnnouncements: '拒绝访问：仅限教师创建公告。',
    validatingTeacherCredentials: '正在验证教师凭证...',
    publishingAs: '发布身份',
    subjectLabel: '科目 / 学科',
    subjectPlaceholder: '例如：数据库、算法...',
    announcementTitleLabel: '公告标题',
    announcementTitlePlaceholder: '例如：考试延期、资料已上传...',
    announcementContentLabel: '公告内容',
    announcementContentPlaceholder: '为学生输入公告的详细内容...',
    publishingAnnouncement: '正在发布公告...',
    publishAnnouncementBtn: '发布到公告栏'
  },
  'Русский': {
    notificationsTitle: 'УВЕДОМЛЕНИЯ',
    newPostTitle: 'НОВАЯ ПУБЛИКАЦИЯ',
    newAnnouncementTitle: 'НОВОЕ ОБЪЯВЛЕНИЕ',
    profileTitle: 'ПРОФИЛЬ',
    commentsTitle: 'Комментарии',
    close: 'Закрыть',
    postsLabel: 'посты',
    registration: 'Регистрационный номер',
    noBio: 'Описание профиля пока отсутствует.',
    message: 'Сообщение',
    repostedBy: 'репост от',
    noReposts: 'Репосты пока отсутствуют.',
    profileNotFound: 'Профиль не найден.',
    back: 'Назад',
    audioCall: 'Аудиозвонок',
    videoCall: 'Видеозвонок',
    blockUser: 'Заблокировать пользователя',
    unblockUser: 'Разблокировать пользователя',
    blockedContact: 'Заблокированный контакт',
    blockedContactDesc: 'Вы заблокировали этого пользователя. Чтобы отправлять текстовые сообщения, вложения, эмодзи или совершать звонки, вам необходимо разблокировать его.',
    recordingVoice: 'Запись голоса...',
    cancel: 'Отмена',
    sendAudio: 'Отправить аудио',
    sendImage: 'Отправить изображение',
    emojis: 'Эмодзи',
    recordVoiceMsg: 'Записать голосовое сообщение',
    yourConversations: 'Ваши диалоги',
    selectContactDesc: 'Выберите контакт на боковой панели, чтобы открыть безопасный и приватный чат.',
    protectedVideoCall: 'Защищенный видеозвонок',
    protectedAudioCall: 'Защищенный аудиозвонок',
    postTitleLabel: 'Заголовок публикации',
    postContentLabel: 'Чем вы хотите поделиться? (Необязательно)',
    postContentPlaceholder: 'Напишите здесь подробности, ссылки или объявления вашей публикации...',
    coverImageLabel: 'Изображение обложки (Необязательно)',
    clickSelectImage: 'Нажмите, чтобы выбрать изображение',
    uploading: 'Загрузка...',
    publishing: 'Публикация...',
    publishBtnText: 'Опубликовать в EduConnect',
    onlyTeachersCanCreateAnnouncements: 'Доступ запрещен: создавать объявления могут только преподаватели.',
    validatingTeacherCredentials: 'Проверка учетных данных преподавателя...',
    publishingAs: 'Публикация от имени',
    subjectLabel: 'Предмет / Дисциплина',
    subjectPlaceholder: 'Пример: БАЗЫ ДАННЫХ, АЛГОРИТМЫ...',
    announcementTitleLabel: 'Заголовок объявления',
    announcementTitlePlaceholder: 'Пример: Экзамен перенесен, Материал доступен...',
    announcementContentLabel: 'Содержание объявления',
    announcementContentPlaceholder: 'Введите подробности объявления для студентов...',
    publishingAnnouncement: 'Публикация объявления...',
    publishAnnouncementBtn: 'Опубликовать на доске'
  },
  'العربية': {
    notificationsTitle: 'الإشعارات',
    newPostTitle: 'منشور جديد',
    newAnnouncementTitle: 'إعلان جديد',
    profileTitle: 'الملف الشخصي',
    commentsTitle: 'التعليقات',
    close: 'إغلاق',
    postsLabel: 'منشورات',
    registration: 'رقم التسجيل',
    noBio: 'لا يوجد عرض تقديمي متاح في النظام بعد.',
    message: 'رسالة',
    repostedBy: 'إعادة نشر من',
    noReposts: 'لم يتم مشاركة أي إعادة نشر بعد.',
    profileNotFound: 'لم يتم العثور على الملف الشخصي.',
    back: 'رجوع',
    audioCall: 'مكالمة صوتية',
    videoCall: 'مكالمة فيديو',
    blockUser: 'حظر المستخدم',
    unblockUser: 'إلغاء حظر المستخدم',
    blockedContact: 'جهة اتصال محظورة',
    blockedContactDesc: 'لقد قمت بحظر هذا المستخدم. لإرسال رسائل نصية أو مرفقات أو رموز تعبيرية أو بدء مكالمات، تحتاج إلى إلغاء حظره.',
    recordingVoice: 'جاري تسجيل الصوت...',
    cancel: 'إلغاء',
    sendAudio: 'إرسال الصوت',
    sendImage: 'إرسال صورة',
    emojis: 'رموز تعبيرية',
    recordVoiceMsg: 'تسجيل رسالة صوتية',
    yourConversations: 'محادثاتك',
    selectContactDesc: 'حدد جهة اتصال في الشريط الجانبي لفتح دردشة آمنة وخاصة.',
    protectedVideoCall: 'مكالمة فيديو آمنة',
    protectedAudioCall: 'مكالمة صوتية آمنة',
    postTitleLabel: 'عنوان المنشور',
    postContentLabel: 'ماذا تريد أن تشارك؟ (اختياري)',
    postContentPlaceholder: 'اكتب هنا تفاصيل أو روابط أو إعلانات منشورك...',
    coverImageLabel: 'صورة الغلاف (اختياري)',
    clickSelectImage: 'انقر لتحديد صورة',
    uploading: 'جاري الرفع...',
    publishing: 'جاري النشر...',
    publishBtnText: 'نشر في EduConnect',
    onlyTeachersCanCreateAnnouncements: 'تم رفض الوصول: يسمح للمعلمين فقط بإنشاء الإعلانات.',
    validatingTeacherCredentials: 'جاري التحقق من أوراق اعتماد المعلم...',
    publishingAs: 'النشر باسم',
    subjectLabel: 'المادة / التخصص',
    subjectPlaceholder: 'مثال: قاعدة بيانات، خوارزميات...',
    announcementTitleLabel: 'عنوان الإعلان',
    announcementTitlePlaceholder: 'مثال: تأجيل الامتحان، المادة متوفرة...',
    announcementContentLabel: 'محتوى الإعلان',
    announcementContentPlaceholder: 'أدخل تفاصيل الإعلان للطلاب...',
    publishingAnnouncement: 'جاري نشر الإعلان...',
    publishAnnouncementBtn: 'نشر على لوحة الإعلانات'
  },
  'हिन्दी': {
    notificationsTitle: 'सूचनाएं',
    newPostTitle: 'नया पोस्ट',
    newAnnouncementTitle: 'नयी सूचना',
    profileTitle: 'प्रोफ़ाइल',
    commentsTitle: 'टिप्पणियाँ',
    close: 'बंद करें',
    postsLabel: 'पोस्ट',
    registration: 'पंजीकरण संख्या',
    noBio: 'सिस्टम में अभी तक कोई परिचय उपलब्ध नहीं है।',
    message: 'संदेश',
    repostedBy: 'यहाँ से रीपोस्ट किया गया',
    noReposts: 'कोई रीपोस्ट साझा नहीं किया गया है।',
    profileNotFound: 'प्रोफ़ाइल नहीं मिली।',
    back: 'वापस',
    audioCall: 'ऑडियो कॉल',
    videoCall: 'वीडियो कॉल',
    blockUser: 'उपयोगकर्ता को ब्लॉक करें',
    unblockUser: 'उपयोगकर्ता को अनब्लॉक करें',
    blockedContact: 'अवरुद्ध संपर्क',
    blockedContactDesc: 'आपने इस उपयोगकर्ता को ब्लॉक कर दिया है। टेक्स्ट संदेश, अटैचमेंट, इमोजी भेजने या कॉल शुरू करने के लिए, आपको उन्हें अनब्लॉक करना होगा।',
    recordingVoice: 'आवाज रिकॉर्ड हो रही है...',
    cancel: 'रद्द करें',
    sendAudio: 'ऑडियो भेजें',
    sendImage: 'छवि भेजें',
    emojis: 'इमोजी',
    recordVoiceMsg: 'वॉयस संदेश रिकॉर्ड करें',
    yourConversations: 'आपकी बातचीत',
    selectContactDesc: 'सुरक्षित और निजी चैट खोलने के लिए साइडबार में एक संपर्क चुनें।',
    protectedVideoCall: 'सुरक्षित वीडियो कॉल',
    protectedAudioCall: 'सुरक्षित ऑडियो कॉल',
    postTitleLabel: 'पोस्ट का शीर्षक',
    postContentLabel: 'आप क्या साझा करना चाहते हैं? (वैकल्पिक)',
    postContentPlaceholder: 'अपने पोस्ट के विवरण, लिंक या घोषणाएं यहाँ लिखें...',
    coverImageLabel: 'कवर छवि (वैकल्पिक)',
    clickSelectImage: 'छवि चुनने के लिए क्लिक करें',
    uploading: 'अपलोड हो रहा है...',
    publishing: 'प्रकाशित हो रहा है...',
    publishBtnText: 'EduConnect पर प्रकाशित करें',
    onlyTeachersCanCreateAnnouncements: 'पहुंच अस्वीकृत: केवल शिक्षक ही सूचनाएं बना सकते हैं।',
    validatingTeacherCredentials: 'शिक्षक क्रेडेंशियल का सत्यापन हो रहा है...',
    publishingAs: 'इस रूप में प्रकाशित हो रहा है',
    subjectLabel: 'विषय / अनुशासन',
    subjectPlaceholder: 'उदा: डेटाबेस, एल्गोरिदम...',
    announcementTitleLabel: 'सूचना का शीर्षक',
    announcementTitlePlaceholder: 'उदा: परीक्षा स्थगित, सामग्री उपलब्ध...',
    announcementContentLabel: 'सूचना की सामग्री',
    announcementContentPlaceholder: 'छात्रों के लिए सूचना का विवरण दर्ज करें...',
    publishingAnnouncement: 'सूचना प्रकाशित हो रही है...',
    publishAnnouncementBtn: 'बोर्ड पर प्रकाशित करें'
  },
  '한국어': {
    notificationsTitle: '알림',
    newPostTitle: '새 게시물',
    newAnnouncementTitle: '새 공지사항',
    profileTitle: '프로필',
    commentsTitle: '댓글',
    close: '닫기',
    postsLabel: '게시물',
    registration: '학번',
    noBio: '등록된 소개글이 없습니다.',
    message: '메시지',
    repostedBy: '리포스트 출처:',
    noReposts: '공유된 리포스트가 없습니다.',
    profileNotFound: '프로필을 찾을 수 없습니다.',
    back: '돌아가기',
    audioCall: '음성 통화',
    videoCall: '영상 통화',
    blockUser: '사용자 차단',
    unblockUser: '사용자 차단 해제',
    blockedContact: '차단된 연락처',
    blockedContactDesc: '이 사용자를 차단했습니다. 텍스트 메시지, 첨부 파일, 이모티콘을 보내거나 통화를 시작하려면 차단을 해제해야 합니다.',
    recordingVoice: '음성 녹음 중...',
    cancel: '취소',
    sendAudio: '음성 전송',
    sendImage: '이미지 전송',
    emojis: '이모티콘',
    recordVoiceMsg: '음성 메시지 녹음',
    yourConversations: '대화 목록',
    selectContactDesc: '사이드바에서 연락처를 선택하여 안전하고 비공개인 대화를 시작하세요.',
    protectedVideoCall: '보안 영상 통화',
    protectedAudioCall: '보안 음성 통화',
    postTitleLabel: '게시물 제목',
    postContentLabel: '무엇을 공유하고 싶으신가요? (선택)',
    postContentPlaceholder: '게시물의 상세 내용, 링크, 공지사항 등을 여기에 적어주세요...',
    coverImageLabel: '커버 이미지 (선택)',
    clickSelectImage: '클릭하여 이미지 선택',
    uploading: '업로드 중...',
    publishing: '게시 중...',
    publishBtnText: 'EduConnect에 게시',
    onlyTeachersCanCreateAnnouncements: '액세스 거부: 교원만 공지사항을 생성할 수 있습니다.',
    validatingTeacherCredentials: '교원 자격 증명 확인 중...',
    publishingAs: '게시자:',
    subjectLabel: '교과 / 과목',
    subjectPlaceholder: '예: 데이터베이스, 알고리즘...',
    announcementTitleLabel: '공지사항 제목',
    announcementTitlePlaceholder: '예: 시험 연기, 자료 배포...',
    announcementContentLabel: '공지사항 내용',
    announcementContentPlaceholder: '학생들을 위한 공지사항의 상세 내용을 입력하세요...',
    publishingAnnouncement: '공지 게시 중...',
    publishAnnouncementBtn: '게시판에 게시'
  }
};

Object.keys(extraTranslations).forEach(lang => {
  if (translations[lang]) {
    Object.assign(translations[lang], extraTranslations[lang]);
  }
});

export function useLanguage() {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('educonnect-lang') || 'Português (BR)';
  });

  useEffect(() => {
    const handleLanguageChange = () => {
      setLang(localStorage.getItem('educonnect-lang') || 'Português (BR)');
    };

    window.addEventListener('educonnect-language-change', handleLanguageChange);
    return () => {
      window.removeEventListener('educonnect-language-change', handleLanguageChange);
    };
  }, []);

  const translate = (key) => {
    const langDict = translations[lang] || translations['Português (BR)'];
    return langDict[key] || key;
  };

  return { lang, translate };
}
